routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Resources
Route::resource('/','MainController');
Route::resource('/product','ProductController');
Route::resource('/mission','MissionController');
Route::resource('/team','TeamController');
Route::resource('/feedback','FeedbackController');
Route::resource('/history','HistoryController');
Route::resource('/news','NewsController');
Route::resource('/event','EventController');
Route::resource('/about','AboutController');
Route::resource('/user','UserController');

Auth::routes();

Route::get('/','MainController@index');

if (Auth::check()) {
	return view('dashboard');
}

Route::get('/29adminPower', 'HomeController@index');

Route::get('/add-product',function(){
	return view('admins.ProductAdd');
});

Route::get('organization', 'MainController@org');
Route::get('news_all', 'MainController@news_all');
Route::get('show_news/{id}', 'MainController@show_news');

Route::get('/new', function () {
    return view('news');
});

resources/views/admins/AboutAdd.blade.php
@extends('adminlte::page')

@section('title', 'Add About Us')

@section('content_header')
    <h1>Add About Us</h1>
@stop

@section('content')
    <form action="{{route('about.store')}}" method="POST">
    	{{csrf_field()}}
    	<div class="row">
    		<div class="col-sm-10">
		    	<div class="input-group">
		    		<span class="input-group-addon">Type</span>
		    		<select class="form-control" name="type" id="type" required>
		    			<option selected disabled>-- Choose One --</option>
		    			<option>Who Are We</option>
		    			<option>Vission</option>
		    		</select>
		    	</div>
    		</div>
    	</div>

    	<div class="row">
    		<div class="col-sm-10">
		    	<div class="input-group">
					<span class="input-group-addon">Description</span>
					<textarea class="form-control content-news" name="content" id="content"></textarea>
				</div>
    		</div>
    	</div>
    	
    	<div class="row">
    		<div class="text-center col-sm-10">
		    	<div class="input-group">
					<input class="btn btn-primary" type="submit" name="submit">
		    	</div>
    		</div>
    	</div>	
    </form>
@stop


@section('js')
    <script type="text/javascript" src="../public/vendor/ckeditor/ckeditor.js"></script>
    <script type="text/javascript">
        $(function(){
            CKEDITOR.replace('content')
        })
    </script>
@stop

resources/views/admins/AboutEdit.blade.php
@extends('adminlte::page')

@section('title', 'Add About Us')

@section('content_header')
    <h1>Add About Us</h1>
@stop

@section('content')
    <form action="{{route('about.update',['about'=>$about->id])}}" method="POST">
    	{{csrf_field()}}
    	<input type="hidden" name="_method" value="PUT">
    	<div class="row">
    		<div class="col-sm-10">
		    	<div class="input-group">
		    		<span class="input-group-addon">Type</span>
		    		<input type="text" class="form-control" name="type" id="type" readonly value="{{$about->type}}">
		    	</div>
    		</div>
    	</div>

    	<div class="row">
    		<div class="col-sm-10">
		    	<div class="input-group">
					<span class="input-group-addon">Content</span>
					<textarea class="form-control content-news" name="content" id="content">{!!$about->content!!}</textarea>
				</div>
    		</div>
    	</div>
    	
    	<div class="row">
    		<div class="text-center col-sm-10">
		    	<div class="input-group">
					<input class="btn btn-primary" type="submit" name="submit">
		    	</div>
    		</div>
    	</div>	
    </form>
@stop


@section('js')
    <script type="text/javascript" src="../../public/vendor/ckeditor/ckeditor.js"></script>
    <script type="text/javascript">
        $(function(){
            CKEDITOR.replace('content')
        })
    </script>
@stop

resources/views/admins/AboutView.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>View About Us</h1>
@stop

@section('content')
	<div class="container-fluid">
		<div class="row">
			<div class="col-sm-2 text-center">Type</div>
			<div class="col-sm-8 text-center">Content</div>
			<div class="col-sm-2 text-center">Action</div>
		</div>
		@if($abouts->isEmpty())
		<div class="row">
			<div class="col-sm-10 text-center">
				<b>No data Found</b>	
			</div>
		</div>
		@else
		    @foreach($abouts as $about)
			    <div class="row">
			    	<div class="col-sm-2 text-center">{{$about->type}}</div>
					<div class="col-sm-8">{!!$about->content!!}</div>
					<div class="col-sm-2 text-center">
						<div class="col-sm-6">
							<a href="{{route('about.edit',['about'=>$about->id])}}" class="btn btn-primary">Edit</a>
						</div>
						<div class="col-sm-6">
							<form action="{{ route('about.destroy', ['about'=>$about->id]) }}" method='POST'>

								{{ csrf_field() }}

								<input type="hidden" name="_method" value="DELETE">
								<input type="submit" class="btn btn-danger red" value="delete">
								
							</form>
						</div>
					</div>
			    </div>
			    <br>
			@endforeach
		@endif
	</div>
@stop

resources/views/admins/EventAdd.blade.php
@extends('adminlte::page')

@section('content_header')
	<h1>Add Event</h1>
@stop

@section('content')
	<form enctype="multipart/form-data" action="{{route('event.store')}}" method="POST">
		{{csrf_field()}}
		<div class="input-group">
			<span class="input-group-addon">Poster</span>
			<input class="form-control" type="file" name="poster" id="poster" accept="image/*" required>
		</div>

		<div class="input-group">
			<span class="input-group-addon"><i class="glyphicon glyphicon-header"></i></span>
			<input class="form-control" type="text" name="title" id="title" required>
		</div>
		
		<div class="row">
			<div class="col-sm-6">
				<div class="input-group">
					<span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i> Start</span>
					<input class="form-control" type="date" name="date_start" id="date_start" required>
				</div>
			</div>

			<div class="col-sm-6">
				<div class="input-group">
					<span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i> End</span>
					<input class="form-control" type="date" name="date_end" id="date_end">
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-sm-6">
				<div class="input-group">
					<span class="input-group-addon"><i class="glyphicon glyphicon-time"></i> Start</span>
					<input class="form-control" type="time" name="time_start" id="time_start" required>
				</div>
			</div>
			<div class="col-sm-6">
				<div class="input-group">
					<span class="input-group-addon"><i class="glyphicon glyphicon-time"></i> End</span>
					<input class="form-control" type="time" name="time_end" id="time_end" required>
				</div>
			</div>
		</div>
		<br>
		<input class="btn btn-primary" type="submit" name="submit">
	</form>
@stop

resources/views/admins/EventView.blade.php
@extends('adminlte::page')

@section('content_header')
	View Events
@stop

@section('content')
	<div class="row text-center">
		<div class="col-sm-2">
			Poster
		</div>
		<div class="col-sm-2">
			Title
		</div>
		<div class="col-sm-2">
			Date
		</div>
		<div class="col-sm-2">
			Time
		</div>
		<div class="col-sm-2">
			Action
		</div>
	</div>

	@if($events->isEmpty())
		No Event Registered
	@else
		@foreach($events as $event)
		<div class="row text-center">
			<div class="col-sm-2">
				<img src="assets/img/events/{{$event->poster}}" style="width: 150px;">
			</div>
			<div class="col-sm-2">
				{{$event->title}}
			</div>
			<div class="col-sm-2">
				@if($event->date_end == NULL)
                    {{date('d F Y', strtotime($event->date_start))}}
                @else
               		{{date('d', strtotime($event->date_start))}} - {{date('d F Y', strtotime($event->date_end))}}
                @endif
			</div>
			<div class="col-sm-2">
				{{date('H:i',strtotime($event->time_start))}} - {{date('H:i',strtotime($event->time_end))}}
			</div>
			<div class="col-sm-2">
				<div class="row">
					<div class="col-sm-6">
						<a href="{{route('event.edit',['event'=>$event->id])}}" class="btn btn-primary">Edit</a>
					</div>
					<div class="col-sm-6">
						<form action="{{ route('event.destroy', ['event'=>$event->id]) }}" method='POST'>
							{{ csrf_field() }}
							<input type="hidden" name="_method" value="DELETE">
							<input type="submit" class="btn btn-danger red" value="delete">
						</form>
					</div>
				</div>
			</div>
		</div>
		@endforeach
	@endif
@stop

resources/views/admins/HistoryEdit.blade.php
@extends('adminlte::page')

@section('title', 'History - Update')

@section('content_header')
    <h1>Update History</h1>
@stop

@section('content')
    <form action="{{route('history.update',['history'=>$history->id])}}" method="POST">
    	{{csrf_field()}}
        <input type="hidden" name="_method" value="PUT">
    	<div class="row">
    		<div class="col-sm-10">
		    	<div class="input-group">
		    		<span class="input-group-addon">Year</span>
		    		<input class="form-control" type="text" name="year" id="year" pattern="[0-9]{4,}" title="Must contain 4 digit of number" value="{{$history->year}}" required>
		    	</div>
    		</div>
    	</div>

    	<div class="row">
    		<div class="col-sm-10">
		    	<div class="input-group">
					<span class="input-group-addon">Description</span>
					<textarea class="form-control" name="history" id="history" rows="4" required>{{$history->history}}</textarea>
				</div>
    		</div>
    	</div>
    	
    	<div class="row">
    		<div class="text-center col-sm-10">
		    	<div class="input-group">
					<input class="btn btn-primary" type="submit" name="submit">
		    	</div>
    		</div>
    	</div>	
    </form>
@stop

@section('js')
    <script type="text/javascript" src="../../public/vendor/ckeditor/ckeditor.js"></script>
    <script type="text/javascript">
        $(function(){
            CKEDITOR.replace('history')
        })
    </script>
@stop

resources/views/admins/HistoryView.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Dashboard</h1>
@stop

@section('content')
	<div class="row" style="margin-bottom: 10px;">
		<div class="col-sm-3 text-center">
			Year
		</div>
		<div class="col-sm-6 text-center">
			History
		</div>
        <div class="col-sm-3 text-center">
            Action
        </div>
	</div>
    @foreach($histories as $history)
    	<div class="row" style="margin-bottom: 10px;">
    		<div class="col-sm-3 text-center">
    			{{$history->year}}
    		</div>	

    		<div class="col-sm-6">
                <p>
                    {!!$history->history!!}
                </p>
    		</div>

            <div class="col-sm-3 text-center">
			<div class="row">
                    <div class="col-sm-6">
                        <a href="{{route('history.edit',['history'=>$history->id])}}" class="btn btn-primary">Edit</a>
                    </div>
                    <div class="col-sm-6">
                        <form action="{{ route('history.destroy', ['history'=>$history->id]) }}" method='POST'>

                            {{ csrf_field() }}

                            <input type="hidden" name="_method" value="DELETE">
                            <input type="submit" class="btn btn-danger red" value="delete">
                            
                        </form>
                    </div>
                </div>
            </div>
    	</div>
    @endforeach
@stop

resources/views/admins/NewsAdd.blade.php
@extends('adminlte::page')

@section('content_header')
	<h1>Add News</h1>
@stop

@section('content')
	<form enctype="multipart/form-data" action="{{route('news.store')}}" method="POST">
		{{csrf_field()}}
		<div class="input-group">
			<span class="input-group-addon">image</span>
			<input class="form-control" type="file" name="image" id="image" accept="image/*" required>
		</div>

		<div class="input-group">
			<span class="input-group-addon"><i class="glyphicon glyphicon-header"></i></span>
			<input class="form-control" type="text" name="title" id="title" required="">
		</div>

		<div class="input-group">
			<span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
			<input class="form-control" type="date" name="date" id="date" required="">
		</div>

		<div class="input-group">
			<span class="input-group-addon">Description</span>
			<textarea class="form-control content-news" name="content" id="content"></textarea>
		</div>

		<input type="submit" name="submit" class="btn btn-primary">
	</form>
@stop

@section('js')
    <script type="text/javascript" src="../public/vendor/ckeditor/ckeditor.js"></script>
    <script type="text/javascript">
        $(function(){
            CKEDITOR.replace('content')
        })
    </script>
@stop

resources/views/admins/NewsEdit.blade.php
@extends('adminlte::page')

@section('content_header')
	<h1>Edit News</h1>
@stop

@section('content')
	<form action="{{route('news.update',['news'=>$news->id])}}" method="POST" enctype="multipart/form-data">
		{{csrf_field()}}
		<input type="hidden" name="_method" value="PUT">

		<div class="row">
			<div class="col-sm-10">
				<div class="input-group">
					<span class="input-group-addon">image</span>
					<input class="form-control" type="file" name="image" id="image" accept="image/*" required>
				</div>		
			</div>
			<div class="col-sm-2">
				<p class="text-danger">*size must less then 1MB</p>
			</div>
		</div>

		

		<div class="input-group">
			<span class="input-group-addon"><i class="glyphicon glyphicon-header"></i></span>
			<input class="form-control" type="text" name="title" id="title" value="{{$news->title}}">
		</div>

		<div class="input-group">
			<span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
			<input class="form-control" type="date" name="date" id="date" value="{{$news->date}}">
		</div>

		<div class="input-group">
			<span class="input-group-addon">Description</span>
			<textarea class="form-control content-news" name="content" id="content">{{$news->content}}</textarea>
		</div>

		<input type="submit" name="submit" class="btn btn-primary">
	</form>
@stop

@section('js')
    <script type="text/javascript" src="../../public/vendor/ckeditor/ckeditor.js"></script>
    <script type="text/javascript">
        $(function(){
            CKEDITOR.replace('content')
        })
    </script>
@stop

resources/views/admins/NewsView.blade.php
@extends('adminlte::page')

@section('content_header')
	<h1>
		View Events
	</h1>
@stop

@section('content')
	<div class="row text-center">
		<div class="col-sm-2">
			Image
		</div>
		<div class="col-sm-2">
			Title
		</div>
		<div class="col-sm-2">
			Date
		</div>
		<div class="col-sm-2">
			Content
		</div>
		<div class="col-sm-2">
			Action
		</div>
	</div>

	@if($news->isEmpty())
		No News Submitted
	@else
		@foreach($news as $news)
		<div class="row text-center">
			<div class="col-sm-2">
				<img src="assets/img/news/{{$news->image}}" style="width: 150px;">
			</div>
			<div class="col-sm-2">
				{{$news->title}}
			</div>
			<div class="col-sm-2">
				{{date('d F Y', strtotime($news->date))}}
			</div>
			<div class="col-sm-2">
				{!! substr($news->content,0,100) !!}
			</div>
			<div class="col-sm-2">
				<div class="row">
					<div class="col-sm-6">
						<a href="{{route('news.edit',['news'=>$news->id])}}" class="btn btn-primary">Edit</a>
					</div>
					<div class="col-sm-6">
						<form action="{{ route('news.destroy', ['news'=>$news->id]) }}" method='POST'>

                            {{ csrf_field() }}

                            <input type="hidden" name="_method" value="DELETE">
                            <input type="submit" class="btn btn-danger red" value="delete">
                            
                        </form>
					</div>
				</div>
			</div>
		</div>
		@endforeach
	@endif
@stop

resources/views/admins/ProductAdd.blade.php
@extends('adminlte::page')

@section('title','Add Product')

@section('content_header')
    <h1>Add Product</h1>
@stop

@section('content')	
	<form enctype="multipart/form-data" action="{{route('product.store')}}" method="POST">
		{{csrf_field()}}
		<div class="row ">
			<div class="col-sm-3">
				<div class="input-group">
					<span class="input-group-addon">Name</i></span>
					<input class="form-control" type="text" name="product_name" id="product_name">
				</div>
			</div>

			<div class="col-sm-1"></div>

			<div class="col-sm-4">
				<div class="input-group">
					<span class="input-group-addon">Logo</i></span>
					<input class="form-control" type="file" name="product_logo" id="product_logo" accept="image/*">
				</div>
			</div>

			<div class="col-sm-1"></div>

			<div class="col-sm-3">
				<div class="input-group">
					<span class="input-group-addon">website</i></span>
					<input class="form-control" type="url" name="product_website" id="product_website" value="https://">
				</div>
			</div>
		</div>
		<br>
		<div class="row">
			<div class="col-sm-6">
				<div class="input-group">
					<span class="input-group-addon">Description</i></span>
					<textarea class="form-control" name="product_about"></textarea>
				</div>
			</div>

			<div class="col-sm-1"></div>

			<div class="col-sm-5">
				<div class="input-group">
					<span class="input-group-addon">Product Main Color</i></span>
					<input class="form-control" type="text" name="product_color" id="product_color" value="#" oninput="change()">
				</div>
				<div style="height: 15px;" id="color"></div>
			</div>
		</div>
		
		<br>
		<div class="row text-center">
			<input type="submit" name="submit" class="btn btn-primary">
		</div>
	</form>
@stop

@section('js')
	<script type="text/javascript">
		function change(){
			var test = $('input[id="product_color"]').val();
			$('div[id="color"]').css('background-color', test);
		}
	</script>
@stop

resources/views/admins/ProductEdit.blade.php
@extends('adminlte::page')

@section('title','Add Product')

@section('content_header')
    <h1>Add Product</h1>
@stop

@section('content')	
	<form enctype="multipart/form-data" action="{{ route('product.update', [$product->id]) }}" method="POST">
		{{csrf_field()}}
		<input type="hidden" name="_method" value="PUT">
		<div class="row ">
			<div class="col-sm-3">
				<div class="input-group">
					<span class="input-group-addon">Name</i></span>
					<input class="form-control" type="text" name="product_name" id="product_name" value="{{$product->product_name}}">
				</div>
			</div>

			<div class="col-sm-1"></div>

			<div class="col-sm-4">
				<div class="input-group">
					<span class="input-group-addon">Logo</i></span>
					<input class="form-control" type="file" name="product_logo" id="product_logo">
				</div>
			</div>

			<div class="col-sm-1"></div>

			<div class="col-sm-3">
				<div class="input-group">
					<span class="input-group-addon">website</i></span>
					<input class="form-control" type="url" name="product_website" id="product_website" value="{{$product->product_website}}">
				</div>
			</div>
		</div>
		<br>
		<div class="row">
			<div class="col-sm-6">
				<div class="input-group">
					<span class="input-group-addon">Description</i></span>
					<textarea class="form-control" name="product_about">{{$product->product_about}}</textarea>
				</div>
			</div>

			<div class="col-sm-1"></div>

			<div class="col-sm-5">
				<div class="input-group">
					<span class="input-group-addon">Product Main Color</i></span>
					<input class="form-control" type="text" name="product_color" id="product_color" value="{{$product->product_color}}" oninput="change()">
				</div>
				<div style="height: 15px;" id="color"></div>
			</div>
		</div>
		<br>
		<div class="row text-center">
			<input type="submit" name="submit" class="btn btn-primary">
		</div>
	</form>
@stop

@section('js')
	<script type="text/javascript">
		function change(){
			var test = $('input[id="product_color"]').val();
			$('div[id="color"]').css('background-color', test);
		}
	</script>
@stop

resources/views/admins/TeamEdit.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Edit Team</h1>
@stop

@section('content')
    <form enctype="multipart/form-data" action="{{ route('team.update', [$team->id]) }}" method="POST">
    	{{csrf_field()}}
        <input type="hidden" name="_method" value="PUT">
    	<div class="row">
    		<div class="col-sm-4">
    			<div class="input-group">
    				<span class="input-group-addon">
    					Image
    				</span>
    				<input class="form-control" type="file" name="profile_photo" id="profile_photo" accept="image/*" required>
    			</div>
    		</div>

    		<div class="col-sm-1"></div>

    		<div class="col-sm-4">
    			<div class="input-group">
    				<span class="input-group-addon">
    					Name
    				</span>
    				<input class="form-control" type="text" name="profile_name" id="profile_name" value="{{$team->profile_name}}">
    			</div>
    		</div>    		
    	</div>

    	<br>

    	<div class="row">
            <div class="col-sm-4">
                <div class="input-group">
                    <span class="input-group-addon">
                        Division
                    </span>
                    <select class="form-control" type="text" name="profile_division" id="profile_division" required oninput="sub()">
                        <option disabled>-- Choose One --</option>

                        @if($team->profile_division == 'DPi')
                            <option selected>
                        @else
                            <option>
                        @endif
                            DPI
                        </option>

                        @if($team->profile_division == 'Marketing')
                            <option selected>
                        @else
                            <option>
                        @endif
                            Marketing
                        </option>

                        @if($team->profile_division == 'Product')
                            <option selected>
                        @else
                            <option>
                        @endif
                            Product
                        </option>

                        @if($team->profile_division == 'Internal')
                            <option selected>
                        @else
                            <option>
                        @endif
                            Internal
                        </option>
                    </select>
                </div>
            </div>

            <div class="col-sm-1"></div>

    		<div class="col-sm-4">
    			<div class="input-group">
                    <span class="input-group-addon">
                        Sub Division
                    </span>
                    <select class="form-control" type="text" name="profile_sub_division" id="profile_sub_division">
                        <option disabled>-- Choose One --</option>
                        {{-- dpi selection --}}
                        @if($team->profile_division == 'DPI')
                            <option class="DPI" selected="">
                        @else
                            <option class="DPI">
                        @endif
                            -
                        </option>

                        {{-- marketing --}}
                        @if($team->profile_sub_division == 'External Event Organizer')
                            <option class="Marketing" selected="">
                        @else
                            <option class="Marketing">
                        @endif
                            External Event Organizer
                        </option>

                         @if($team->profile_sub_division == 'Public Relation')
                            <option class="Marketing" selected="">
                        @else
                            <option class="Marketing">
                        @endif
                            Public Relation
                        </option>

                        {{-- product --}}
                        @if($team->profile_sub_division == 'Learning and Training')
                            <option class="Product" selected="">
                        @else
                            <option class="Product">
                        @endif
                            Learning and Training
                        </option>

                        @if($team->profile_sub_division == 'Fave Solution')
                            <option class="Product" selected="">
                        @else
                            <option class="Product">
                        @endif
                            Fave Solution
                        </option>

                        @if($team->profile_sub_division == 'File Magz')
                            <option class="Product" selected="">
                        @else
                            <option class="Product">
                        @endif
                            File Magz
                        </option>

                        {{-- internal --}}
                        @if($team->profile_sub_division == 'Research And Development')
                            <option class="Internal" selected="">
                        @else
                            <option class="Internal">
                        @endif
                            Research And Development
                        </option>

                         @if($team->profile_sub_division == 'Human Resource Development')
                            <option class="Internal" selected="">
                        @else
                            <option class="Internal">
                        @endif
                            Human Resource Development
                        </option>                  
                    </select>
                </div>
            </div>
    	</div>

        <br>

        <div class="row">
            <div class="col-sm-9 text-center">
                <div class="input-group">
                    <span class="input-group-addon">
                        Position
                    </span>
                    <select class="form-control" name="profile_position" id="profile_position" required>
                        <option disabled>-- Choose One --</option>
                        {{-- dpi selection --}}
                        @if($team->profile_position == 'Chief Executive Officer')
                            <option class="DPI" selected>
                        @else
                            <option class="DPI">
                        @endif
                            Chief Executive Officer
                        </option>

                        @if($team->profile_position == 'Chief Finance Officer')
                            <option class="DPI" selected>
                        @else
                            <option class="DPI">
                        @endif
                            Chief Finance Officer
                        </option>

                        @if($team->profile_position == 'Chief Marketing Officer')
                            <option class="DPI" selected>
                        @else
                            <option class="DPI">
                        @endif
                            Chief Marketing Officer
                        </option>

                        @if($team->profile_position == 'Chief Product Officer')
                            <option class="DPI" selected>
                        @else
                            <option class="DPI">
                        @endif
                            Chief Product Officer
                        </option>

                        @if($team->profile_position == 'Chief Internal Officer')
                            <option class="DPI" selected>
                        @else
                            <option class="DPI">
                        @endif
                            Chief Internal Officer
                        </option>

                        {{-- SubDiv selection --}}
                        @if($team->profile_position == 'Manager')
                            <option class="sub" selected>
                        @else
                            <option class="sub">
                        @endif
                            Manager
                        </option>

                        @if($team->profile_position == 'Staff')
                            <option class="sub" selected>
                        @else
                            <option class="sub">
                        @endif
                            Staff
                        </option>

                    </select>
                </div>
            </div>
        </div>

    	<br>

    	<div class="row text-center">
    		<div class="col-sm-9">
    			<button type="submit" class="btn btn-primary">
    				Submit
    			</button>
    		</div>
    	</div>
    </form>
@stop


@section('js')
    <script type="text/javascript">
        $('.DPI').hide();
        $('.Marketing').hide();
        $('.Product').hide();
        $('.Internal').hide();
        $('.sub').hide();

        function sub(){
            $('.DPI').hide();
            $('.Marketing').hide();
            $('.Product').hide();
            $('.Internal').hide();
            $('.sub').hide();

            $('#profile_sub_division').prop('selectedIndex',0);

            var select = document.getElementById('profile_division').value;

            if(select == 'DPI'){
                $('#profile_sub_division').prop('selectedIndex',1);
                $('#profile_position').prop('selectedIndex',0);
                $('.'+select).show();
            }
            else{
                $('#profile_sub_division').prop('selectedIndex',0);
                $('#profile_position').prop('selectedIndex',0);
                $('.'+select).show();
                $('.sub').show();
            }
        }

    </script>
@stop

resources/views/admins/UserEdit.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Edit Profile</h1>
@stop

@section('content')
    <form action="{{route('user.update',['user'=>$user->id])}}" method="POST">
    	{{csrf_field()}}
        <input type="hidden" name="_method" value="PUT">
    	<div class="row">
    		<div class="col-sm-5">
		    	<div class="input-group">
		    		<span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
		    		<input class="form-control" type="text" name="email" id="email" value="{{$user->email}}" required>
		    	</div>
    		</div>
    	</div>

    	<div class="row">
    		<div class="col-sm-5">
		    	<div class="input-group">
					<span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
					<input class="form-control" type="password" name="password" id="password" required>
				</div>
    		</div>
    	</div>
    	<br>
    	
    	<div class="row">
    		<div class="text-center col-sm-10">
		    	<div class="input-group">
					<input class="btn btn-primary" type="submit" name="submit">
		    	</div>
    		</div>
    	</div>	
    </form>
@stop